package com.yanglq;
import com.yanglq.entity.User;
import java.io.Console;
// 规则1，如果有钱就买一瓶喝掉
rule "r001"
    //no-loop true
	salience 3
	when
		$u:User(money>0);
	then
		System.out.println("Spare money:" + $u.getMoney() + ",use 1$ buy one and drink");
		System.out.println(System.getProperty("file.encoding"));
		$u.setKp($u.getKp() + 1);
		$u.setMoney($u.getMoney() - 1);
		$u.setTotals($u.getTotals() + 1);
		update($u);
end

// 规则2，如果空瓶数大于2则换购1瓶（兑换成1元钱）
rule "r002"
	salience 2
	when
		$u:User(kp>=2);
	then
		System.out.println("Empty bottle number:" + $u.getKp() + ",2bottle=1$");
		$u.setKp($u.getKp() - 2);
		$u.setMoney($u.getMoney() + 1);
		update($u);
end

// 规则3，打印已经喝掉的数量
rule "r003"
	salience 1
	when
		$u:User();
	then
		System.out.println("totalNumber:" + $u.getTotals());
end